import StyledComponentsRegistry from '@/lib/registry'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'kisosk Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={inter.className} >
        {/* <main className='flex min-h-screen flex-col items-center justify-between p-24'> */}
        {/* <main className='flex min-h-screen flex-col items-center justify-between '> */}
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
        {/* </main> */}
      </body>
    </html >
  )
}
